}
tG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\Enum\Enum_SDKEventType.csutf-8y
pG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\Enum\Enum_SDKState.csutf-8Ç
yG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\Enum\Enum_SDKStateEventType.csutf-8~
uG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\Enum\Enum_VideoConnType.csutf-8Ä
wG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\Enum\Enum_VideoPTZControl.csutf-8É
zG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\Enum\Enum_VideoPlayEventType.csutf-8
vG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\Enum\Enum_VideoPlayState.csutf-8t
kG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\ProgConstants.csutf-8t
kG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\ProgParameter.csutf-8~
uG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\Properties\AssemblyInfo.csutf-8Ñ
{G:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\Properties\Resources.Designer.csutf-8r
iG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\PubDelegate.csutf-8o
fG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\SDKState.csutf-8r
iG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\SDK_BlueSDK.csutf-8s
jG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\SDK_EzvizSDK.csutf-8w
nG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\SDK_EzvizSDK_Old.csutf-8w
nG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\SDK_HikClientSDK.csutf-8q
hG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\SDK_HuaMai.csutf-8p
gG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\SDK_JCSDK.csutf-8u
lG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\SDK_SKVideoSDK.csutf-8y
pG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\SDK_TalkManagerSDK.csutf-8p
gG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\SDK_XMSDK.csutf-8t
kG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\UTF8Marsgaler.csutf-8É
zG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoBackplayWindow.Designer.csutf-8z
qG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoBackplayWindow.csutf-8Ç
yG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoBasicClass\Base64coder.csutf-8Ö
|G:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoBasicClass\Enum_TalkModel.csutf-8ç
ÉG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoBasicClass\RemoteVideoRecordInfo.csutf-8Å
xG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoBasicClass\SoundClass.csutf-8ã
ÅG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoBasicClass\VideoPlayEventValue.csutf-8á
~G:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoBasicClass\VideoPlaySetting.csutf-8Ä
wG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoChannelList.Designer.csutf-8w
nG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoChannelList.csutf-8Ö
|G:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoEncoderAsync\EncodedVideo.csutf-8Ä
wG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoEncoderAsync\Encoder.csutf-8î
äG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoEncoderAsync\QuickAudioEncodingCommands.csutf-8î
äG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoEncoderAsync\QuickVideoEncodingCommands.csutf-8Ç
yG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoEncoderAsync\VideoFile.csutf-8
vG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPTZControl.Designer.csutf-8v
mG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPTZControl.csutf-8{
rG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlay\IVideoPlay.csutf-8
vG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlay\VideoPlay_AXIS.csutf-8Ç
yG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlay\VideoPlay_BuleSky.csutf-8Ä
wG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlay\VideoPlay_Ezviz.csutf-8Å
xG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlay\VideoPlay_HikDVR.csutf-8Ä
wG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlay\VideoPlay_Shike.csutf-8
vG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlay\VideoPlay_XMai.csutf-8Ä
wG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlay\Video_HikStream.csutf-8ó
çG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayGroupControl_ExtendedControl .Designer.csutf-8é
ÑG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayGroupControl_ExtendedControl .csutf-8î
äG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayGroupControl_MultiPicture1.Designer.csutf-8ã
ÅG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayGroupControl_MultiPicture1.csutf-8ç
ÉG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayGroupControls_Basic.Designer.csutf-8É
zG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayGroupControls_Basic.csutf-8è
ÖG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayGroupControls_Basic_1.Designer.csutf-8Ö
|G:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayGroupControls_Basic_1.csutf-8í
àG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayGroupControls_PTZAndTalk.Designer.csutf-8à
G:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayGroupControls_PTZAndTalk.csutf-8ñ
åG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayGroupControls_VideoInfoList1.Designer.csutf-8ç
ÉG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayGroupControls_VideoInfoList1.csutf-8
vG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayWindow.Designer.csutf-8v
mG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayWindow.csutf-8ê
ÜG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoRecordBackplay\IVideoRecordBackplay.csutf-8•
õG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoRecordBackplay\VideoPlayback\VideoBackPlay_AmpFileParser.csutf-8î
äG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoRecordBackplay\VideoRecordBackplay_AXIS.csutf-8ó
çG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoRecordBackplay\VideoRecordBackplay_BlueSky.csutf-8î
äG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoRecordBackplay\VideoRecordBackplay_XMAI.csutf-8ä
ÄG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoRecordBackplayWindow.Designer.csutf-8Ä
wG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoRecordBackplayWindow.csutf-8}
tG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoRecordInfoConvert.csutf-8
vG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoRecordList.Designer.csutf-8v
mG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoRecordList.csutf-8ê
ÜG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoRemoteBackplay\IVIdeoRemoteBackplay.csutf-8{
rG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoTalk\IVideoTalk.csutf-8Ñ
{G:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoTalk\VideoTalk_HikStream.csutf-8å
ÇG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoTalk\VideoTalk_HikStream_Client.csutf-8Ä
wG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoTalk\VideoTalk_Shike.csutf-8Ä
wG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoTalkControl.Designer.csutf-8w
nG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoTalkControl.csutf-8å
ÇG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoTalkControlManyChannel.Designer.csutf-8Ç
yG:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoTalkControlManyChannel.csutf-8Æ
£G:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\obj\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.csgb2312Æ
£G:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\obj\Debug\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.csgb2312Æ
£G:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\obj\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.csgb2312∞
•G:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\obj\Release\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.csgb2312∞
•G:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\obj\Release\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.csgb2312∞
•G:\Working\Maintenance\VideoPlayControl\VideoPlayControl\VideoPlayControl\VideoPlayControl\obj\Release\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.csgb2312